version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  ai-api:
    build: ./ai-api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    depends_on:
      - db
      - redis
    volumes:
      - ./ai-api:/app
      - ./conversations:/app/conversations

  whatsapp-bot:
    build: ./whatsapp-bot
    ports:
      - "3000:3000"
    environment:
      - API_URL=${API_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - ai-api
    volumes:
      - ./whatsapp-bot/session:/app/session
      - ./conversations:/app/conversations

volumes:
  postgres_data: